# Semana 3 - Joan Jácome

In [53]:
import numpy as np
import ipyparallel as ipp
%matplotlib inline

In [2]:
c = ipp.Client()
c.ids

[0, 1, 2, 3]

In [4]:
c[1:3].apply_sync(lambda: "Hola Joan")

['Hola Joan', 'Hola Joan']

In [5]:
c[:].map_sync(lambda x,y,z: x+y+z, range(10), range(10), range(10))

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [24]:
%%timeit
x = 2**5
for i in np.arange(int(x**0.5)+1):
    x%i
    
#grafica esta función

C:\Users\Joan\Anaconda2\lib\site-packages\ipykernel\__main__.py:259: RuntimeWarning: divide by zero encountered in long_scalars


The slowest run took 38.01 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 8.68 µs per loop


In [41]:
def PrimeQA(x):
    import numpy as np
    return all(x % i for i in np.arange(int(x**0.5)+1)[2:])

#grafica esta funcion

In [42]:
PrimeQA(2**7)

False

In [43]:
c[:].apply_sync(PrimeQA, 2**7)

[False, False, False, False]

In [44]:
dview = c[:]

In [45]:
2**np.arange(7)

array([ 1,  2,  4,  8, 16, 32, 64])

In [46]:
%timeit dview.map_sync(PrimeQA, 2**np.arange(25))

10 loops, best of 3: 72.3 ms per loop


In [57]:
%%timeit

for i in 2**np.arange(25):
    x % i

The slowest run took 4.84 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 18.2 µs per loop


In [26]:
np.all?

In [48]:
np.all(np.array([x % i for i in np.arange(int(x**0.5)+1)[2:]]))

False

In [77]:
def PrimeQB(x):
    import numpy as np
    return np.all(np.array([x % i for i in np.arange(np.int(x**0.5)+1)[2:]]))

#grafica esta funcion

In [61]:
%timeit dview.map_sync(PrimeQB, 2**np.arange(25))

10 loops, best of 3: 78.8 ms per loop


In [63]:
np.mod(24,12)

0

In [64]:
24%12

0

In [65]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [66]:
for med in np.arange(12,20):
    print np.mod(np.arange(24), med) 

[ 0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12  0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13  0  1  2  3  4  5  6  7  8  9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14  0  1  2  3  4  5  6  7  8]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16  0  1  2  3  4  5  6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17  0  1  2  3  4  5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18  0  1  2  3  4]


In [68]:
np.array([hora % 12 for hora in np.arange(24)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11])

In [69]:
def PrimeQC(x):
    import numpy as np
    lista = np.arange(np.int(x**0.5)+1)[2:]
    residuos = np.mod(x,lista)
    return np.all(residuos)

#grafica esta funcion

In [70]:
np.mod(12,np.arange(24)[2:])

array([ 0,  0,  0,  2,  0,  5,  4,  3,  2,  1,  0, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12])

In [80]:
%timeit dview.map_sync(PrimeQB, 2**np.arange(10))

10 loops, best of 3: 71 ms per loop


In [81]:
%timeit dview.map_sync(PrimeQC, 2**np.arange(10))

10 loops, best of 3: 69 ms per loop
